exclude: [README.md]
  
title: Apply COV-STATIS to neuroimaging data
description: This is a companion website
theme: jekyll-theme-minimal

# Navigation
navigation:
- text: Home page
  internal: true
  url: ./
- text: Add a new first page
  internal: true
  url: page1
- text: Add a new second page
  internal: true
  url: page2



