project:
  type: website
  output-dir: docs

website:
  title: "covSTATIS"
  description: This is a companion website to the paper [DOI]
  favicon: logo.png
  navbar:
    left:
      - href: pages/page1.qmd
        text: Reproducible example
      - href: pages/page2.qmd
        text: Other extensions
      - href: pages/about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source
