project:
  type: website
  output-dir: docs

website:
  title: "covSTATIS"
  description: This is a companion website to (the paper)[https://doi.org/10.48550/arXiv.2403.14481]
  favicon: logo.png
  navbar:
    left:
      - href: pages/tutorial.qmd
        text: Reproducible example
      - href: pages/extensions.qmd
        text: Other extensions
      - href: pages/about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source
