---
title: "About"
---
\newcommand\latexcode[1]{#1}

<iframe width="100%" height="400" src="https://lookerstudio.google.com/embed/reporting/1ec6b33e-a1bd-4f2c-896d-25f4cd05fbc4/page/dhjBE" frameborder="0" style="border:0" allowfullscreen sandbox="allow-storage-access-by-user-activation allow-scripts allow-same-origin allow-popups allow-popups-to-escape-sandbox" frameborder="0" style="border:0" allowfullscreen></iframe>

## Tutorial & manuscript:

### Giulia Baracchini

I am finishing up my PhD in Cognitive Neuroscience at the Montreal Neurological Institute at McGill University in Montreal, Canada. I love asking questions about things I don't understand (all things brain) and trying to find answers that require exploration across desperate research fields. My primary research topic is fMRI BOLD signal variability. I basically investigate what all the variance in brain signals is and why it matters for brain function and organization. Given my approach to science, I would say this topic chose me. Variance in the variance! 

<i class='far fa-envelope-open'></i>E-mail: [giulia.baracchini@mail.mcgill.ca](mailto:giulia.baracchini@mail.mcgill.ca)

### Ju-Chi Yu

I am a post-doctoral research fellow at Centre for Addiction and Mental Health (CAMH). My work focuses on developing advanced multivariate methods to integrate and examine the relationships between structural and functional brain connectivity. Prior to joining CAMH, I received my Ph.D. in Cognition & Neuroscience from the University of Texas at Dallas, where she focused on developing advanced multivariate methods (with sparsification and for novel applications) to analyze neuroscience data (including behavioral data, genetics data, fMRI data, and resting-state fMRI data).

<i class='far fa-envelope-open'></i>E-mail: [Ju-Chi.Yu@camh.ca](mailto:Ju-Chi.Yu@camh.ca)

## covSTATIS source code:

### DistatisR package

+ [CRAN](https://cran.r-project.org/web/packages/DistatisR/index.html) - by Herv&eacute; Abdi & Derek Beaton
  + Version: 1.1.1
  + Published: 2022-12-05
  + [help file](https://cran.r-project.org/web/packages/DistatisR/DistatisR.pdf)

+ [Version under development](https://github.com/HerveAbdi/DistatisR) - by Herv&eacute; Abdi, Derek Beaton, Vincent Guillemot & Ju-Chi Yu

## Credit statement for the paper:
+ Giulia Baracchini: Conceptualization, Software, Formal Analysis, Data Curation, Writing - Original Draft, Writing - Review and Editing, Visualization. 

+ Ju-Chi Yu: Conceptualization, Software, Formal Analysis, Writing - Original Draft, Writing - Review and Editing. 

+ Jenny Rieck: Software, Formal Analysis, Data Curation, Writing - Review and Editing. 

+ Derek Beaton: Software, Writing - Review and Editing. 

+ Vincent Guillemot: Software, Writing - Review and Editing. 

+ Cheryl Grady: Resources, Writing - Review and Editing. 

+ Herv&eacute; Abdi: Software, Writing - Review and Editing. 

+ R. Nathan Spreng: Writing - Review and Editing, Supervision.

## Website credit

### Vincent Guillemot