title: Apply COV-STATIS to neuroimaging data
description: This is a companion website
theme: jekyll-theme-minimal

website:
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.md
      - page1/page1.md
      - page2/page2.md

# Navigation
navigation:
- text: Home page
  internal: true
  url: ./
- text: Add a new first page
  internal: true
  url: page1
- text: Add a new second page
  internal: true
  url: page2



